In [0]:
# List operations
family = ['father',1.73,'mother',1.68,'son',1.71,'daughter',1.7]

# subsetting 

In [2]:
family[4]

'son'

In [3]:
family[-1]

1.7

In [4]:
family[7]

1.7

In [5]:
# list slicing  rule : [start:end] with start inclusive and end exclusive
family

['father', 1.73, 'mother', 1.68, 'son', 1.71, 'daughter', 1.7]

In [6]:
family[3:5]

[1.68, 'son']

In [7]:
family[1:4]

[1.73, 'mother', 1.68]

In [8]:
family[:4]

['father', 1.73, 'mother', 1.68]

In [9]:
family[5:]

[1.71, 'daughter', 1.7]

In [10]:
# List manipulations
family

['father', 1.73, 'mother', 1.68, 'son', 1.71, 'daughter', 1.7]

In [11]:
#changing list elements
family[7] = 1.69
family

['father', 1.73, 'mother', 1.68, 'son', 1.71, 'daughter', 1.69]

In [12]:
family[6:] = ['grandfather',1.72]
family

['father', 1.73, 'mother', 1.68, 'son', 1.71, 'grandfather', 1.72]

In [13]:
# adding elements to list
family = family + ['daughter',1.69]
family

['father',
 1.73,
 'mother',
 1.68,
 'son',
 1.71,
 'grandfather',
 1.72,
 'daughter',
 1.69]

In [14]:
# deleting elements from list
del(family[4:6])
family

['father', 1.73, 'mother', 1.68, 'grandfather', 1.72, 'daughter', 1.69]

In [15]:
# appending to list
family.append('son')
family
family.append(1.71)
family

['father',
 1.73,
 'mother',
 1.68,
 'grandfather',
 1.72,
 'daughter',
 1.69,
 'son',
 1.71]

In [16]:
# removing from list
family.remove('grandfather')
family


['father', 1.73, 'mother', 1.68, 1.72, 'daughter', 1.69, 'son', 1.71]

In [17]:
family.remove(1.72)
family

['father', 1.73, 'mother', 1.68, 'daughter', 1.69, 'son', 1.71]

In [18]:
family.index('son')


6

In [19]:
family.pop(6)

'son'

In [20]:
family

['father', 1.73, 'mother', 1.68, 'daughter', 1.69, 1.71]

In [21]:
# inserting to a list
family.insert(6,'son')
family

['father', 1.73, 'mother', 1.68, 'daughter', 1.69, 'son', 1.71]

In [0]:
# Python OOP
class Employee:
  raise_rate = 1.8
  counter = 0
  def __init__(self,name,surname,salary): #constructor
     self.name = name
     self.surname = surname
     self.salary = salary
     self.email = name + surname + "@asd.com"
     Employee.counter = Employee.counter + 1
  def giveNameSurname(self):
    return self.name + " " + self.surname
  def perform_raise(self):
    self.salary = self.salary + self.salary * self.raise_rate  


In [23]:
# class variable
employee1 = Employee("ali", "veli",100) 
print("First salary: ",employee1.salary)
employee1.perform_raise()
print("New salary: ",employee1.salary)

employee2 = Employee("ayse", "hatice",200) 
employee3 = Employee("ayse", "yelda",600) 
employee4 = Employee("eren", "hilal",500)

First salary:  100
New salary:  280.0


In [24]:
employee_list = [employee1,employee2,employee3,employee4]

maximum_salary = -1
index = -1
for each in employee_list:
    if(each.salary>maximum_salary):
        maximum_salary = each.salary
        index = each
        
print(maximum_salary)
print(index.giveNameSurname())

600
ayse yelda


In [25]:
 #importing
import numpy as np

# numpy basics
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])  # 1*15 vector

print(array.shape)

(15,)


In [26]:
a = array.reshape(3,5)
print("shape: ",a.shape)
print("dimension: ", a.ndim)

shape:  (3, 5)
dimension:  2


In [27]:
print("data type: ",a.dtype.name)
print("size: ",a.size)

data type:  int64
size:  15


In [29]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 5]]


In [30]:
zeros = np.zeros((3,4))

zeros[0,0] = 5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.empty((2,3))

array([[2.4885723e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [33]:
a = np.arange(10,55,5)
print(a)

[10 15 20 25 30 35 40 45 50]


In [38]:
a = np.linspace(10,50,20)
print(a)


[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]


In [35]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

# element wise prodcut
print(a*b)


[[ 1  4  9]
 [16 25 36]]


In [36]:
a.dot(b.T)

array([[14, 32],
       [32, 77]])

In [0]:
a = np.random.random((5,5))*10

In [0]:
print(a.sum())
print(a.max())
print(a.min())

In [0]:
print(a.sum(axis=0))

In [0]:
print(a.sum(axis=1))